server:
  port: 8080
spring:
  application:
    name: "university-registration"
  devtools:
    add-properties: false
  profiles:
    default: default
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-doc
adapters:
  persistence:
    host: localhost
    port: 5432
    database: university
    username: theask
    password: elAllan!!12345
    schema: public
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"